# Generated by Django 4.2.2 on 2023-06-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('genero', models.CharField(max_length=10)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('zona', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=100)),
                ('escolaridad', models.CharField(max_length=50)),
                ('ocupacion', models.CharField(max_length=100)),
                ('tipo_recoleccion', models.CharField(max_length=50)),
                ('ciudad_votacion', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=100)),
                ('mesa', models.CharField(max_length=100)),
            ],
        ),
    ]
